footprint: [[0.5, 0.4], [-0.5, 0.4], [-0.5, -0.4], [0.5, -0.4]] 
footprint_padding: 0.01

robot_base_frame: /base_link
update_frequency: 1.0
publish_frequency: 3.0
transform_tolerance: 0.5


obstacle_layer:
  enabled:              true
  max_obstacle_height:  1.0
  origin_z:             0.0
  z_resolution:         0.05
  z_voxels:             20
  unknown_threshold:    15
  mark_threshold:       0
  obstacle_range: 3
  raytrace_range: 5
  publish_voxel_map: true
  observation_sources:  scan 
  scan:
    sensor_fram: pandar
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: -0.5
    max_obstacle_height: 1.0

inflation_layer:
  enabled:              true  
  inflation_radius:     0.8

static_layer:
  map_topic:            /map
  subscrib_to_updates:    true
  enabled:              true
  

