obstacle_range: 2.5
raytrace_range: 2.0
footprint: [[0.45,0.31], [-0.45,0.31], [-0.45,-0.31], [0.45,-0.31]]
inflation_radius: 0.15
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: laser_scan_sensor #bump
laser_scan_sensor: {

    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
}
